source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
target 'paris' do
pod 'AFNetworking', '~> 3.0'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'SDWebImage', '~>3.8'

pod 'Bugly'
pod 'UMengAnalytics'
pod 'UMengUShare/Social/SMS'
pod 'UMengUShare/UI'
pod 'UMengUShare/Social/Sina'
pod 'UMengUShare/Social/QQ'
pod 'UMengUShare/Social/WeChat'

end
