export const SET_TASKLIST='SET_TASKLIST';
export const SET_CURRENTASK='SET_CURRENTASK';
export const SET_CALLBACKLIST='SET_CALLBACKLIST';
export const SET_CURRENTCALLBACK='SET_CURRENTCALLBACK';
export const SET_REPORTUID='SET_REPORTUID';